.TH ALIASER 1 "March 2023"
.SH NAME
aliaser \- A CLI utility to create and manage aliases
.SH SYNOPSIS
aliaser [options]
.SH DESCRIPTION
This utility allows you to create and manage aliases for your shell.
.SH OPTIONS
.TP
\-p, \--path <path>
Path to assign alias to
.TP
\-a, \--alias <alias>
Alias to assign to path
.TP
\-h, \--help
Show help message and exit
.SH EXAMPLES
aliaser -p ~ -a home

aliaser -a home -p ~
.SH AUTHOR
Your Name
.SH REPORTING BUGS
<https://github.com/your-repo/issues>

